version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/10.1-alpine-postgis-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: professors_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Running Tests
          command: bundle exec rspec
