version: 2
jobs:
  build:
    machine:
      ruby:
        version: 2.4.0
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Running Tests
          command: bundle exec rspec
